version: '3'

services:

  mongo:
    image: mongo:4.4-bionic
    ports:
      - "27018:27017"
    volumes:
      - nmdc_runtime_dev_mongo_data:/data/db
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: root

  terminus:
    image: terminusdb/terminusdb-server:v4.2.0
    ports:
      - "6364:6363"
    volumes:
      - nmdc_runtime_terminus_storage:/app/terminusdb/storage
    environment:
      TERMINUSDB_SERVER_PORT: 6363
      TERMINUSDB_ADMIN_PASS: root
      TERMINUSDB_AUTOLOGIN_ENABLED: "true"
      TERMINUSDB_HTTPS_ENABLED: "true"


volumes:
  nmdc_runtime_dev_mongo_data:
    driver: local
  nmdc_runtime_terminus_storage:
    driver: local