site_name: nmdc-runtime docs
site_url: https://microbiomedata.github.io/nmdc-runtime/
theme:
  name: material
nav:
  - index.md
  - Jobs:
    - jobs/emsl-translation-etl.md
    - jobs/gold-translation-etl.md
    - jobs/jgi-translation-etl.md
  - contributing.md
  - admin.md
markdown_extensions:
  - admonition
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format