name: mkdocs
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.repository.fork == false
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout mkdocs-material
        uses: actions/checkout@v2
        with:
          repository: squidfunk/mkdocs-material-insiders
          token: ${{ secrets.GH_TOKEN_MKDOCS_MATERIAL_INSIDERS }}
          path: mkdocs-material
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install ./mkdocs-material
      - run: mkdocs gh-deploy --force





